#pragma once
/*
 * Animated weather icons: Meteocons Lottie files rendered by ThorVG.
 *
 * Why Lottie rather than a font or a PNG sequence:
 *   - LVGL fonts are single-colour alpha masks, so they cannot be "realistic".
 *   - A pre-rendered frame sequence at 96px would be ~660 KB PER ICON and
 *     locked to one size. The whole 20-icon Lottie set is 373 KB and scales.
 *   - ThorVG ships inside LVGL 9.2, so there is no extra dependency.
 *
 * Assets live on the SPIFFS `storage` partition, generated by
 * `python tools/build_icons.py` and named by WeatherFlow's own icon slug, so
 * there is no translation table at runtime.
 *
 * Cost per widget: one ARGB8888 buffer of size*size*4 bytes, allocated in
 * PSRAM. A 96px icon is 36 KB; a 56px forecast icon is 12.5 KB.
 */

#include <stdbool.h>
#include "esp_err.h"
#include "lvgl.h"

/* Mounts the SPIFFS partition. Call once before creating any icon. */
esp_err_t wx_icons_init(void);

/* Creates an icon widget. `animate` false renders a single representative
 * frame and stops -- use it for the forecast strip, where seven simultaneous
 * vector animations would cost far more CPU than they are worth. */
lv_obj_t *wx_icon_create(lv_obj_t *parent, int size, bool animate);

/* Swaps the artwork. Safe to call every tick: a repeat of the current slug is
 * ignored, so this does not reload the JSON 60 times a minute.
 * Returns false if neither the slug nor the unknown fallback could load. */
bool wx_icon_set(lv_obj_t *icon, const char *slug);

/* True when the slug means precipitation, for tinting the forecast column. */
bool wx_icon_is_wet(const char *slug);

/* Stop ThorVG while LIVE is covered. Hidden widgets still animate. */
void wx_icon_set_paused(lv_obj_t *icon, bool paused);
