idf_component_register(
    SRCS
        "main.c"
        "wx_state.c"
        "tempest_udp.c"
        "tempest_rest.c"
        "net.c"
        "indoor.c"
        "display.c"
        "ui/ui.c"
        "ui/wx_icons.c"
        "ui/settings.c"
        "ui/graphs.c"
        "history.c"
        "config.c"
        "diag.c"
        "ota.c"
    INCLUDE_DIRS
        "."
        "ui"
    REQUIRES
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        lwip
        esp_http_client
        esp-tls
        json
        esp_lcd
        driver
        esp_timer
        spiffs
        esp_app_format
        app_update
        spi_flash
        esp_http_server
)
